// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebServer.Models.WebServerDB;

public partial class WebServerDBContext : DbContext
{
    public WebServerDBContext(DbContextOptions<WebServerDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ExchangeReportStockDayAll> ExchangeReportStockDayAll { get; set; }

    public virtual DbSet<User> User { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Chinese_Taiwan_Stroke_CI_AS");

        modelBuilder.Entity<ExchangeReportStockDayAll>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Exchange__3214EC074DC7BC60");

            entity.HasIndex(e => new { e.Code, e.TradeDate }, "IX_ExchangeReportStockDayAll_Code_TradeDate");

            entity.HasIndex(e => new { e.TradeDate, e.Code }, "IX_ExchangeReportStockDayAll_TradeDate_Code");

            entity.Property(e => e.Change).HasColumnType("decimal(10, 4)");
            entity.Property(e => e.ClosingPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Code)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.HighestPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.LowestPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.OpeningPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TradeDate)
                .HasMaxLength(7)
                .IsUnicode(false)
                .IsFixedLength();
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.ID)
                .ValueGeneratedNever()
                .HasComment("用戶的唯一識別碼");
            entity.Property(e => e.AccessFailedCount).HasComment("失敗訪問計數");
            entity.Property(e => e.Account)
                .HasMaxLength(50)
                .HasComment("用戶的帳號名稱");
            entity.Property(e => e.AccountNormalize)
                .HasMaxLength(50)
                .HasComment("帳號名稱的標準化版本（用於一致性）");
            entity.Property(e => e.Birthday).HasComment("用戶的生日");
            entity.Property(e => e.CreatedDT)
                .HasComment("創建時間戳")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .HasComment("用戶的電子郵件地址  ");
            entity.Property(e => e.EmailNormalize)
                .HasMaxLength(50)
                .HasComment("電子郵件地址的標準化版本");
            entity.Property(e => e.LockoutEnabled).HasComment("是否啟用鎖定功能");
            entity.Property(e => e.LockoutEnd)
                .HasComment("鎖定結束時間")
                .HasColumnType("datetime");
            entity.Property(e => e.Mobile)
                .HasMaxLength(100)
                .HasComment("用戶的手機號碼");
            entity.Property(e => e.ModifiedDT)
                .HasComment("最後修改時間戳")
                .HasColumnType("datetime");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasComment("用戶的姓名");
            entity.Property(e => e.PasswordHash)
                .HasMaxLength(256)
                .HasComment("用戶密碼的哈希值");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}