// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class ExchangeReportStockDayAll
{
    public int Id { get; set; }

    public string TradeDate { get; set; } = null!;

    public string Code { get; set; } = null!;

    public string Name { get; set; } = null!;

    public long? TradeVolume { get; set; }

    public long? TradeValue { get; set; }

    public decimal? OpeningPrice { get; set; }

    public decimal? HighestPrice { get; set; }

    public decimal? LowestPrice { get; set; }

    public decimal? ClosingPrice { get; set; }

    public decimal? Change { get; set; }

    public int? TransactionCount { get; set; }
}