// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebServer.Models.WebServerDB;

public partial class User
{
    /// <summary>
    /// 用戶的唯一識別碼
    /// </summary>
    public Guid ID { get; set; }

    /// <summary>
    /// 用戶的帳號名稱
    /// </summary>
    public string Account { get; set; } = null!;

    /// <summary>
    /// 帳號名稱的標準化版本（用於一致性）
    /// </summary>
    public string AccountNormalize { get; set; } = null!;

    /// <summary>
    /// 用戶的電子郵件地址  
    /// </summary>
    public string Email { get; set; } = null!;

    /// <summary>
    /// 電子郵件地址的標準化版本
    /// </summary>
    public string EmailNormalize { get; set; } = null!;

    /// <summary>
    /// 用戶密碼的哈希值
    /// </summary>
    public string PasswordHash { get; set; } = null!;

    /// <summary>
    /// 用戶的姓名
    /// </summary>
    public string Name { get; set; } = null!;

    /// <summary>
    /// 用戶的手機號碼
    /// </summary>
    public string? Mobile { get; set; }

    /// <summary>
    /// 用戶的生日
    /// </summary>
    public DateOnly? Birthday { get; set; }

    /// <summary>
    /// 鎖定結束時間
    /// </summary>
    public DateTime? LockoutEnd { get; set; }

    /// <summary>
    /// 是否啟用鎖定功能
    /// </summary>
    public bool LockoutEnabled { get; set; }

    /// <summary>
    /// 失敗訪問計數
    /// </summary>
    public int AccessFailedCount { get; set; }

    /// <summary>
    /// 創建時間戳
    /// </summary>
    public DateTime CreatedDT { get; set; }

    /// <summary>
    /// 最後修改時間戳
    /// </summary>
    public DateTime? ModifiedDT { get; set; }
}